# Generated by Django 3.1.2 on 2020-12-26 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('core', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentordersdesigner',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.designer'),
        ),
        migrations.AddField(
            model_name='recentordersdesigner',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.merchant'),
        ),
        migrations.AddField(
            model_name='recentordersdesigner',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
        migrations.AddField(
            model_name='product_saved',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.merchant'),
        ),
        migrations.AddField(
            model_name='product_saved',
            name='product',
            field=models.ManyToManyField(to='product.Product'),
        ),
        migrations.AddField(
            model_name='orders',
            name='cart_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
        migrations.AddField(
            model_name='items',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cart.cart'),
        ),
        migrations.AddField(
            model_name='items',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.merchant'),
        ),
    ]
